# Generated by Django 5.2.5 on 2025-08-14 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('document', models.FileField(upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='avatars/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10),
        ),
        migrations.AlterField(
            model_name='learningtypetag',
            name='name',
            field=models.CharField(choices=[('Подготовка к ОГЭ/ЕГЭ', 'Подготовка к ОГЭ/ЕГЭ'), ('Помощь с домашним заданием', 'Помощь с домашним заданием'), ('Углубленное изучение', 'Углубленное изучение')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjecttag',
            name='name',
            field=models.CharField(choices=[('math', 'Mathematics'), ('history', 'History'), ('computer_science', 'Computer Science')], max_length=50),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('interests', models.TextField(blank=True)),
                ('learning_goals', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('verification_documents', models.FileField(blank=True, upload_to='verification_docs/')),
                ('certificates', models.ManyToManyField(blank=True, to='accounts.certificate')),
                ('learning_types', models.ManyToManyField(blank=True, to='accounts.learningtypetag')),
                ('subjects', models.ManyToManyField(blank=True, to='accounts.subjecttag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
                ('available_times', models.ManyToManyField(to='accounts.timeslot')),
            ],
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
